version: 0.0
os: linux
files:
  - source: / # depoly source path
    destination: /var/www/html # deploy server path
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: cd_install_dependencies
      timeout: 300
      runas: root
    - location: cd_start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: cd_stop_server
      timeout: 300
      runas: root