version: 0.0
os: linux
files:
  - source: / # depoly source path
    destination: /java # deploy server path
file_exists_behavior: OVERWRITE
permissions:
  - object: /java
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: app_install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: app_start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: app_stop_server
      timeout: 300
      runas: root